# run_power_sim.ps1
# Gate-level simulation runner for CPU power analysis.
# Generates a power.vcd file from the 8-stage balanced pipeline post-compilation gate-level netlist.

# Set execution directory to this script's path
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$originalDir = Get-Location
Set-Location $scriptDir

# 1. Environment & Pre-requisites Checks
Write-Host "Checking environment and prerequisites..." -ForegroundColor Cyan

# Check if vsim (ModelSim/QuestaSim) is available in PATH
if (-not (Get-Command vsim -ErrorAction SilentlyContinue)) {
    Write-Host "Error: ModelSim/QuestaSim executable 'vsim' not found in system PATH." -ForegroundColor Red
    Set-Location $originalDir
    exit 1
}

# Verify gate-level netlist exists
$netlistPath = Join-Path $scriptDir "simulation/questa/cpu.vo"
if (-not (Test-Path $netlistPath)) {
    Write-Host "Error: Gate-level netlist not found at $netlistPath." -ForegroundColor Red
    Write-Host "Please compile the Quartus project first to generate the netlist." -ForegroundColor Yellow
    Set-Location $originalDir
    exit 1
}

# Verify testbench exists
$tbPath = Join-Path $scriptDir "tb_top.sv"
if (-not (Test-Path $tbPath)) {
    Write-Host "Error: Testbench not found at $tbPath." -ForegroundColor Red
    Set-Location $originalDir
    exit 1
}

# Paths to dependencies
$iniSource = Join-Path $scriptDir "../sim/scripts/modelsim.ini"
$iniDest = Join-Path $scriptDir "modelsim.ini"

# Copy modelsim.ini if it exists in sim/scripts to ensure correct settings
if (Test-Path $iniSource) {
    Write-Host "Copying modelsim.ini for simulation configuration..." -ForegroundColor Gray
    Copy-Item -Path $iniSource -Destination $iniDest -Force | Out-Null
}

# Create the ModelSim run script (power_sim.do) dynamically
$doFilePath = Join-Path $scriptDir "power_sim.do"
$doContent = @"
# power_sim.do
# Automatically generated by run_power_sim.ps1

onerror {quit -code 1 -f}
onbreak {quit -f}

# Initialize/Clean work library
if [file exists work] {
    vdel -lib work -all
}
vlib work

# Compile gate-level netlist
vlog -work work simulation/questa/cpu.vo

# Compile top-level testbench
vlog -work work tb_top.sv

# Load simulation with visibility access and Altera/Intel simulation libraries
vsim -voptargs="+acc" -L fiftyfivenm_ver -L altera_ver -L altera_mf_ver -L 220model_ver -onfinish exit work.tb_top

# Set up VCD dumping
vcd file power.vcd
vcd add -r /tb_top/dut/*

# Run simulation
run -all

# Exit ModelSim
quit -f
"@

Set-Content -Path $doFilePath -Value $doContent -Encoding Ascii

Write-Host "Starting ModelSim gate-level simulation..." -ForegroundColor Cyan

# Run vsim in batch mode
# Using -l vsim.log to capture compilation details in case of errors
$process = Start-Process vsim `
    -ArgumentList "-batch", "-l", "vsim.log", "-do", "power_sim.do" `
    -PassThru -NoNewWindow -Wait `
    -ErrorAction SilentlyContinue

$exitCode = 0
$timeoutOccurred = $false
if ($null -eq $process) {
    Write-Host "Error: Failed to start vsim process." -ForegroundColor Red
    $exitCode = 1
} elseif (-not $process.HasExited) {
    $timeoutOccurred = $true
    $process | Stop-Process -Force -ErrorAction SilentlyContinue | Out-Null
    $exitCode = -1
} else {
    $exitCode = $process.ExitCode
}

# 2. Cleanup Phase
Write-Host "Cleaning up unnecessary generated files..." -ForegroundColor Cyan

# Files/dirs to remove
$filesToRemove = @(
    "power_sim.do",
    "modelsim.ini",
    "vsim.log",
    "transcript",
    "vsim.wlf"
)

foreach ($file in $filesToRemove) {
    $p = Join-Path $scriptDir $file
    if (Test-Path $p) {
        Remove-Item -Path $p -Force -ErrorAction SilentlyContinue | Out-Null
    }
}

# Remove work directory
$workDir = Join-Path $scriptDir "work"
if (Test-Path $workDir) {
    Remove-Item -Path $workDir -Recurse -Force -ErrorAction SilentlyContinue | Out-Null
}

# Verify output
$vcdPath = Join-Path $scriptDir "power.vcd"
if ($exitCode -eq 0 -and -not $timeoutOccurred -and (Test-Path $vcdPath) -and (Get-Item $vcdPath).Length -gt 0) {
    Write-Host "Simulation completed successfully!" -ForegroundColor Green
    Write-Host "VCD file generated: $vcdPath ($((Get-Item $vcdPath).Length) bytes)" -ForegroundColor Green
    Set-Location $originalDir
    exit 0
} else {
    Write-Host "Simulation failed (Exit Code: $exitCode, Timeout: $timeoutOccurred)." -ForegroundColor Red
    if (Test-Path $vcdPath) {
        Write-Host "VCD file was generated but may be incomplete or empty." -ForegroundColor Yellow
    } else {
        Write-Host "VCD file was NOT generated." -ForegroundColor Red
    }
    Set-Location $originalDir
    exit 1
}
